add FirestormPrism
atomicptr/dauntless-builder-reforged pull request #150
Opened 2020-06-05 08:30 UTC by leghort

add the FirestormPrism for repeater weapons

2020-06-05 08:47 UTC, atomicptr requested changes
I suppose the yarn.lock changes are just an update? Beyond the typo in the name, it looks good tyvm :)

2020-06-05 08:47 UTC, atomicptr commented on data/parts/repeater/prisms/FirestormPrism.yml
> +name: FirestormPrism
This should probably be "Firestorm Prism". Don't forget to reset/rebuild the map :).

2020-06-06 00:51 UTC, leghort commented on data/parts/repeater/prisms/FirestormPrism.yml
> +name: FirestormPrism
Oups my bad, and how's that ?

2020-06-06 08:43 UTC, atomicptr approved these changes

2020-06-06 08:44 UTC, atomicptr commented
Looks good, tyvm

2020-06-06 08:44 UTC, merged

2020-06-06 08:44 UTC, atomicptr commented on data/parts/repeater/prisms/FirestormPrism.yml
> +name: FirestormPrism
Yeah I'll just squash the merge anyway :)