Add elemental filter for weapon and armor, Issue #124
atomicptr/dauntless-builder-reforged pull request #165
Opened 2020-09-23 02:40 UTC by BenjinYap

**What I did:**
Added elemental filter for weapon and armor selection.

**Why I did it:**
I wanted to help.

**Mockups, screenshots, evidence:**
![image](https://user-images.githubusercontent.com/6952853/93956388-14ebcd00-fd20-11ea-832e-4b37d41fffd8.png)
![image](https://user-images.githubusercontent.com/6952853/93956252-b45c9000-fd1f-11ea-8f62-76f50b6a09db.png)
![image](https://user-images.githubusercontent.com/6952853/93956276-c807f680-fd1f-11ea-8f54-08db10459940.png)

**Is this related to an open issue?**
https://github.com/atomicptr/dauntless-builder/issues/124

2020-09-25 09:42 UTC, atomicptr requested changes
Hey, thank you very much for your PR :)!

I have a few nit picks, if you resolve them I'd love to merge this.

2020-09-25 09:42 UTC, atomicptr commented on src/components/ItemSelectModal.jsx
> +    getElementOptions() {
Since the elements probably won't change very often, I'd prefer a static list like with "getSlotOptions();"

2020-09-25 09:42 UTC, atomicptr commented on src/components/ItemSelectModal.jsx
> +        //armor or weapon that isn't repeater
Please add a space between the comment marker (//) and the first letter, just for consistency :)

2020-09-25 09:42 UTC, atomicptr commented on src/components/ItemSelectModal.jsx
> +        if(this.isType("Armour") || (this.isType("Weapon") && (this.state.weaponTypeFilter === null || this.state.weaponTypeFilter.value !== "Repeater"))) {
This line is a bit too complicated, might be easier to digest to do something like this:

```javascript
const isRepeater = this.state.weaponFilter !== null && this.state.weaponTypeFilter.value === "Repeater";

if (this.isType("Armour") || (this.isType("Weapon") && !isRepeater) {
    // ....
}
```

At least I can understand this now without thinking too much :hugs:.

2020-09-26 02:04 UTC, BenjinYap commented on src/components/ItemSelectModal.jsx
> +    getElementOptions() {
Not sure if you would prefer replacing the function entirely with just a static list, but I kept it as a function just to be consistent with the others.

2020-09-26 08:21 UTC, atomicptr approved these changes
Looks good, thank you very much :)

2020-09-26 08:21 UTC, merged