Refactor structure & Developer friendly packages / webpack
atomicptr/dauntless-builder-reforged pull request #21
Opened 2018-06-23 00:22 UTC by Rassell

Refactor structure  & Developer friendly packages / webpack

**What I did:**
In order to make it more easier to develop some basic restructure should be done, I think container / component is the best approach

**Why I did it:**
As a developer basic structure of a project is very important to understand it and also to start working.
Notice that also a lot of "eslint" (with airbnb configuration I think as a guideline) is needed in order to maintain some code rules / styles

**Fixes issue (include link):**
-

**Mockups, screenshots, evidence:**
-

**Is this related to an open issue?**
-

2018-06-23 09:18 UTC, atomicptr commented
Guess moving everything to src makes sense, since there is no other logic beyond the react app :). I used a template from work where src is usually occupied by the backend logic, but you're right it's better this way.

A few change I'd like to see though:

* Delete view/, I don't quite see why it's still there.
* 404.html should also move into src/, cuz that thing is very important for making Github like SPAs
* Also you should adjust the deploy script in scripts/deploy.sh to cp src/*.html instead of *.html or else changes in the HTML files will no longer be build :)

Besides those points it looks good.

2018-06-23 09:29 UTC, Rassell commented
About the view/ it's because was my first time working on github and I forgot/didn't know about "forking" first and was trying to modify this repo 💯 

Now I'm working on setting eslint with the airbnb config / adding jest to run test and later on will focus on new features / resolving bugs 👍

2018-06-23 09:45 UTC, atomicptr commented
I've just noticed that an index.html is created in dist/ but the deploy script is still copying the one from src/index.html which results in a non working Github Pages build (since it doesn't include the webpack built js file). You can test this by running the deploy script (but I'd remove the push for testing) and then go into the deploy directory and just use ``http-serve``.

2018-06-23 10:05 UTC, Rassell commented
Yes, my bad. The idea it's to let this plugin of webpack do the work:

```js
    plugins: [new HtmlWebPackPlugin({
        template: './src/index.html',
    })],
```

It will inject the tag to the html on build and when we are developing, ex on build for prod:

```html
...
</script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
<script type="text/javascript" src="dauntless-builder.js"></script>
```

2018-06-23 10:12 UTC, atomicptr commented
Don't forget that this is mostly run by Github Pages, which means you can't rely on anything beyond pure file delivery on their end. The 404.html is important because Github Pages isn't designed with SPAs in mind, meaning if I go to a page via /b/buildId it will run the 404.html file which has a script in it that redirects you to the index.html containing the original url path. Removing the 404.html isn't an option and the script tag has to be in there at build time (which is what travis is doing).

2018-06-23 10:15 UTC, Rassell commented
Didn't know that was running on Github Pages, let me solve that.

2018-06-23 10:19 UTC, Rassell commented
OK, didn't know about the GitHub Pages hosting, then I wont touch the 404 but index.html on dist with the script tag should be fine as it have it after build (before deployment) 👍

2018-06-26 09:25 UTC, Rassell commented
updated with the latest changes, working atm on eslint, after that I will try to refactor some parts of the app that have duplicated code like ModalItemListItemComponent.jsx

2018-06-26 09:34 UTC, atomicptr commented
If you do other things please make seperate PRs for them. All that this PR currently does is adding webpack-dev-server (which also seems to be deprecated?) and html webpack plugin thingy, right?

2018-06-26 09:40 UTC, Rassell commented
Yes i will create a separate pr, no worries

Mmmmm maybe the version is deprecated, but the package itself it's not... 

Also some configuration to the webpack to use maps to make more easier the debugging on dev tools but yeah more or less the other things you already make it to src so there is no too much changes 👍

2018-06-26 10:19 UTC, atomicptr commented
![image](https://user-images.githubusercontent.com/674705/41905304-07c7179e-793b-11e8-9f9f-5e7fd8d1acd0.png)

Well I kinda read this as "is deprecated". The maps would be def. useful tho.

2018-06-26 10:26 UTC, Rassell commented
you are right sir, didn't check the repo from long time ago (always working with it and on the webpack documentation says nothing about that) moving to webpack-serve

2018-06-26 10:51 UTC, Rassell commented
btw I recommend you jest for unit test:

https://medium.com/airbnb-engineering/unlocking-test-performance-migrating-from-mocha-to-jest-2796c508ec50

2018-06-26 10:54 UTC, atomicptr requested changes

2018-06-26 10:54 UTC, atomicptr commented on webpack.config.js
> +    mode: process.argv.indexOf("--production") > -1 ? "production" : "development",
Why have you readded this?

2018-06-26 10:54 UTC, atomicptr commented on package.json
> +    "webpack-dev-server": "^3.1.4",
Still a dependency ;)?

2018-06-26 10:54 UTC, atomicptr commented on package.json
> +    "html-webpack-plugin": "^3.2.0",
Have you figured out a way to use this without breaking the Github Pages?

2018-06-26 10:57 UTC, atomicptr commented
Dunno if changing to jest makes a huge difference for the <10 tests we have :). Will read that article tho.

2018-06-26 10:58 UTC, Rassell commented on webpack.config.js
> +    mode: process.argv.indexOf("--production") > -1 ? "production" : "development",
Its needed for webpack-serve as it doesnt have a dev flag to pass to webpack

2018-06-26 11:03 UTC, closed without merging

2018-06-26 11:03 UTC, atomicptr commented
Huh? Reason why you closed it?